### ISSUE TITLE
multiline string output problem

### ISSUE THREAD

**Issue by orsio-monte** [nikita-volkov/yc-cli.github-action#1]
Hi!

I don't understand how I need to use output with multiline.
I want to get a list of compute instances and then use it later.

My jobs:
```
collect_list_servers:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.servers.outputs.output }}

    steps:
    - name: collect list servers
      id: servers
      uses: nikita-volkov/yc-cli.github-action@v1.0.1
      with:
        key: ${{ secrets.SA_GITHUB_KEY }}
        args: --folder-id **** compute instance list
```
and I see it in Actions log:

> Error: Unable to process file command 'output' successfully.
> Error: Invalid format '|          ID          |         NAME          |    ZONE ID    | STATUS  |  EXTERNAL IP   | INTERNAL IP  |'
